# ── Identity stack secrets (prompts/security/17_02) ───────────────────────────
# OpenLDAP / Keycloak admin passwords, the OIDC client secret and the LDAP user
# passwords live in Vault KV — never in .env, never in bootstrap.ldif.
# Values are generated by scripts/identity-secrets.sh; Terraform owns only the
# mount, the read policy and the AppRole the one-shot identity-secrets-init
# container logs in with (pattern from Editors Factory, prompts 01_07).

resource "vault_mount" "kv" {
  path        = "secret"
  type        = "kv"
  options     = { version = "2" }
  description = "Durin KV v2 — platform secrets (identity stack)"
}

resource "vault_policy" "durin_identity_secrets" {
  name = "durin-identity-secrets"

  policy = <<-EOT
    # Read-only, identity secrets only.
    path "secret/data/durin/identity/*" {
      capabilities = ["read"]
    }
  EOT
}

# Used once per identity-stack start by identity-secrets-init, which revokes its
# own token after rendering the secrets. Short token, non-renewable.
resource "vault_approle_auth_backend_role" "durin_identity_secrets" {
  backend        = vault_auth_backend.approle.path
  role_name      = "durin-identity-secrets"
  token_policies = [vault_policy.durin_identity_secrets.name]
  token_ttl      = 300
  token_max_ttl  = 300
  secret_id_ttl  = 0 # local lab; stored in .secrets/vault/identity-secret-id (gitignored)
}

output "approle_durin_identity_secrets_role_id" {
  description = "AppRole role_id for identity-secrets-init (written to .secrets/ by scripts/identity-secrets.sh)"
  value       = vault_approle_auth_backend_role.durin_identity_secrets.role_id
}

# ── Web Console BFF (prompts/frontend/01_02) ──────────────────────────────────
# The Nuxt BFF is a confidential OIDC client; it needs exactly one secret. The
# one-shot ui-secrets-init container logs in with this AppRole, renders
# oidc-client-secret for durin-ui and revokes its token. durin-ui itself never
# holds a Vault token and cannot read the other identity secrets.

resource "vault_policy" "durin_ui_secrets" {
  name = "durin-ui-secrets"

  policy = <<-EOT
    # The OIDC client secret for client durin-backend — nothing else.
    path "secret/data/durin/identity/oidc-client-secret" {
      capabilities = ["read"]
    }
  EOT
}

resource "vault_approle_auth_backend_role" "durin_ui" {
  backend        = vault_auth_backend.approle.path
  role_name      = "durin-ui"
  token_policies = [vault_policy.durin_ui_secrets.name]
  token_ttl      = 300
  token_max_ttl  = 300
  secret_id_ttl  = 0 # local lab; stored in .secrets/vault/ui-secret-id (gitignored)
}

output "approle_durin_ui_role_id" {
  description = "AppRole role_id for ui-secrets-init (written to .secrets/ by scripts/identity-secrets.sh)"
  value       = vault_approle_auth_backend_role.durin_ui.role_id
}
